version: "3"
services:
  chavez:
    build: .
    container_name: "chavez"
    depends_on:
      - postgres
    environment:
      DATABASE_USER: "postgres"
      DATABASE_PASS: "postgres"
      DATABASE_NAME: "chavez_dev"
      DATABASE_HOST: "chavez-postgres"
      SECRET_KEY_BASE: "asdkjflhakjslfdhakjslhfjakdshfkajldshfalkjsfhalkjsfhklsajhfklsajfhkjla"
      LIVE_VIEW_SALT: "aasdfhaksfhalksjfhalksfhlkjasfdhlkafsdkjalkjshfkaljshfkjaldsfhklj"
      CHECK_ORIGIN: "//localhost"
      HOSTNAME: "localhost"
      PORT: "4001"
    ports:
      - "4001:4001"

  postgres:
    container_name: "chavez-postgres"
    image: library/postgres:12.5
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "chavez_dev"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
